on:
  workflow_dispatch:

env:
  EXE_NAME: gen-anoma-keys

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup toolchain install stable --profile minimal

      - name: build project
        run: cargo build --release

      - name: create release tarball
        run: |
          tar zcf ${{ env.EXE_NAME }}_macos-aarch64.tar.gz -C target/release ${{ env.EXE_NAME }}

      - name: set version to version.current output variable
        id: version
        run: echo "current=$(target/release/${{ env.EXE_NAME }} --version | head -n 1 | sed -E 's/[^0-9]+(.*)/\1/')" >> $GITHUB_OUTPUT

      - name: set tag.value to tag for release
        id: tag
        run: echo "value=v${{ steps.version.outputs.current }}" >> $GITHUB_OUTPUT

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.value }}
          commit: "main"
          name: "${{ steps.tag.outputs.value }}"
          artifacts: ${{ env.EXE_NAME }}_macos-aarch64.tar.gz
          artifactErrorsFailBuild: true
